### PR TITLE
Release pyDARNio

### PR DESCRIPTION
**Pull request by RemingtonRohel**
# Scope 

- Fixes initialization of int arrays to NaN's when restructuring Borealis files from site to array
- Fixes conversion from HDF5 to DMAP:
  - Records with multiple beams can now be converted
  - Correctly checks blanked_samples for both Borealis v0.5 and older files, and Borealis v0.6 files
  - No longer replaces last 10 lag0 samples for rawacf data

## Approval

**Number of approvals:** *3*
**Due Date:** *January 21st, 2022*

## Test

- [x] Test on RPM Linux (OpenSuse, Fedora, RedHat)
- [ ] Test on Debian Linux (Ubuntu)
- [x] Test on Mac OSX
- [ ] Test on Windows (if possible)

To test HDF5 to DMAP conversion:

```python3
from pydarnio import BorealisConvert
filename = # path to bfiq or rawacf file
borealis_filetype = # 'bfiq' or 'rawacf'
dmap_filename = # path where you want to store dmap file
borealis_converter = BorealisConvert(filename, borealis_filetype,
dmap_filename, borealis_file_structure='site' or 'array')
```
Sample HDF5 files can be found here: https://drive.google.com/drive/folders/1j37Ez6JY_IlNAYXx2kG6IGR3aWzhMNMi. Test all files, as some are Borealis v0.5 and some are v0.6.

To test site to array restructuring:

```python3
from pydarnio import BorealisRead
filename = # path to HDF5
borealis_filetype = 'rawacf' or 'bfiq' or 'antennas_iq'
borealis_reader = BorealisRead(filename, borealis_filetype, borealis_file_structure='site')
arrays = borealis_reader.arrays
```

Verify that this error is not raised: `Error restructuring BorealisRawacfv0_5 from site to array style: cannot convert float NaN to integer`
Try with an antennas_iq, bfiq, and rawacf file, if possible.

To test multi-beam record conversion:

```python3
import pydarnio

infile = "path to borealis file with multi-beam records"
file_type = "rawacf" or "bfiq"
file_structure = "site" or "array"
sdarn_file = "path to output sdarn file"

converter = pydarnio.BorealisConvert(infile, file_type, sdarn_file, borealis_file_structure=file_structure)
```

Plot with pyDARN to verify that conversion was successful. For rawacf data, you can find instructions here: https://pydarn.readthedocs.io/en/main/user/range_time/
Contact remington.rohel@usask.ca for multi-beam data.

To test lag0 replacement:

```python3
import pydarnio
import numpy as np

borealis_file = "path to borealis file"
sdarn_file = "location to save dmap file"
converter = pydarnio.BorealisConvert(borealis_file, 'rawacf', sdarn_file)

# Get the far-range lag0 DMAP data
sdarn_dict = converter.sdarn_dict
acfd = sdarn_dict[0]['acfd']
corrs = acfd[:, :, 0] + 1j * acfd[:, :, 1]
far_ranges = corrs[-10:, 0]

# Get the far-range alternate lag0 HDF5 data
combf = sdarn_dict[0]['combf']
words = combf.split()
# record timestamp stored in combf field
index = words.index('record') + 1
timestamp = words[index]
reader = pydarnio.BorealisRead(borealis_file, 'rawacf', borealis_file_structure='site')
records = reader.records
record = records[timestamp]
main_acfs = record['main_acfs']
main_acfs = main_acfs.reshape(record['correlation_dimensions'])
alt_lag0 = main_acfs[0, :, -1]
far_ranges_alt = alt_lag0[-10:]

# Get the far-range lag0 data from the HDF5 file
far_ranges_lag0 = main_acfs[0, -10:, 0]

# Correct for scaling factor and normalization
far_ranges_alt *= ((np.iinfo(np.int16).max**2 / (record['data_normalization_factor']**2))
far_ranges_lag0 *= ((np.iinfo(np.int16).max**2 / (record['data_normalization_factor']**2))

# far_ranges should match far_ranges_lag0, but not match far_ranges_alt
if not np.allclose(far_ranges, far_ranges_alt) and np.allclose(far_ranges, far_ranges_lag0):
    print("Success! No lag0 replacement")
else:
    print("Failure. DMAP lag0 does not match HDF5 lag0 data.")
```

Any HDF5 rawacf file is sufficient for testing.

### CODE REVIEW

**Comment by kevinkrieger** [comment]
I get different results for the files 20211006.2132.00.sas.a.rawacf.dmap  and the dmap I generate from 20211006.2132.00.sas.0.rawacf.hdf5.site, and the differences are not only in the combf, but in some data arrays.

OpenSuSe 15.3
Linux aware 5.3.18-59.27-preempt #1 SMP PREEMPT Tue Oct 5 10:00:40 UTC 2021 (7df2404) x86_64 x86_64 x86_64 GNU/Linux

Code used:
```
from pydarnio import BorealisConvert
#filename = '/home/kevin/Downloads/20201011.2028.52.703525.cly.0.rawacf.hdf5.site'
#filename = '/home/kevin/Downloads/20210815.2116.00.sas.0.rawacf.hdf5.site'
filename = '/home/kevin/Downloads/20211006.2132.00.sas.0.rawacf.hdf5.site'
#filename = '/home/kevin/Downloads/20211006.2132.00.sas.a.rawacf.dmap'
#dmap_filename = '/home/kevin/Downloads/20201011.2028.52.703525.cly.0.rawacf'
#dmap_filename = '/home/kevin/Downloads/20210815.2116.00.sas.0.rawacf'
dmap_filename = '/home/kevin/Downloads/20211006.2132.00.sas.0.rawacf'
#dmap_filename = '/home/kevin/Downloads/20211006.2132.00.sas.a.rawacf'
borealis_filetype = 'rawacf' # 'bfiq' or 'rawacf'
borealis_converter = BorealisConvert(filename, borealis_filetype, dmap_filename, borealis_file_structure='site')
```

And then I used the following commands to determine if there were differences:
```
dmapdump -d 20211006.2132.00.sas.a.rawacf.dmap > f1.txt
dmapdump -d 20211006.2132.00.sas.0.rawacf > f2.txt
diff f1.txt f2.txt
```
And there appear to be differences in data arrays.

**Comment by kevinkrieger** [comment]
Tested site to array without issues.

Tested multi-beam data:
From the file: 20211213.2034.52.pgr.0.rawacf.avg16 which was generated by:

```
import pydarnio

infile = "/home/dataman/widebeam_3tx/20211213/multi_record/20211213.2034.52.pgr.0.rawacf.hdf5.site.avg16"
file_type = "rawacf" or "bfiq"
file_structure = "site" or "array"
sdarn_file = "/home/krieger/20211213.2034.52.pgr.0.rawacf.avg16"

converter = pydarnio.BorealisConvert(infile, file_type, sdarn_file, borealis_file_structure=file_structure)
```

Plot for beam 0 (the rest are similar):
bm0_20211213 2034 52 pgr 0 rawacf avg16

**Comment by kevinkrieger** [comment]
Tested far lag0 replacement with file: 20211231.0000.00.inv.0.rawacf.hdf5.site and 20211231.0000.00.inv.0.rawacf generated from it using the code:

```
#!/bin/env python3

import pydarnio
import numpy as np
fname = '20211231.0000.00.inv.0.rawacf.hdf5.site'
dmap_name = '20211231.0000.00.inv.0.rawacf'

directory = "/home/krieger/pyDARNio"
borealis_site_file = f"{directory}/{fname}"
sdarn_file = f"{directory}/{dmap_name}"

converter = pydarnio.BorealisConvert(borealis_site_file, "rawacf", sdarn_file, 0, borealis_file_structure='site')

# lag0 data from the dmap files acfd data
acfs = converter.sdarn_dict[0]['acfd']
corrs = acfs[:, :, 0] + 1j * acfs[:, :, 1]
far_ranges = corrs[-10:, 0]

main_acfs = converter.arrays['main_acfs']

sdarn_dict = converter.sdarn_dict
reader = pydarnio.BorealisRead(borealis_site_file, "rawacf", borealis_file_structure='site')
records = reader.records
combf = sdarn_dict[0]['combf']
words = combf.split()
# record timestamp stored in combf field
index = words.index('record') + 1
timestamp = words[index]
record = records[timestamp]

main_acfs = record['main_acfs']

main_acfs = main_acfs.reshape(record['correlation_dimensions'])

# Get the lag0 for first beam, far ranges
far_lag0 = main_acfs[0, -10:, 0]

# Get the alternate lag0 values (last lag) for first beam, far ranges
far_alt_lag0 = main_acfs[0, -10:, -1]

# Correct with normalization factor
max_int16 = np.iinfo(np.int16).max

far_lag0 *= (max_int16 ** 2 / (record['data_normalization_factor'] ** 2))
far_alt_lag0 *= (max_int16 ** 2 / (record['data_normalization_factor'] ** 2))

if not np.allclose(far_ranges, far_alt_lag0) and np.allclose(far_ranges, far_lag0):
	print("Success")
else:
	print("Failure")

```

It printed out 'Success'

**Review by kevinkrieger — APPROVED** [review]

**Review by carleyjmartin — COMMENTED** [review]
Installed with pip3 through git for this branch. 
No issues installing. 
Tested on MacOS with python v3.9.9

HDF5 to DMAP conversion: ran code provided, makes new files for three provided hdf5 files, no errors.

Site to array restructure: ran code provided, no output at all so no error shown, arrays parameter printed out and looks fine for the cly site and sas 2116 site files. The sas 2132 site file has a lot of empty values in the dictionary, I don't know if that is on purpose or is a problem?

Multibeam conversion: used the file 20211213.2034.52.pgr.0.rawacf.hdf5.site.avg16 to test on. I couldn't convert it to fitacf to plot and look at the data in a range-time plot, so that might be an issue? (RST just absolutely crashed when I tried) but I plotted ACF data that looked reasonable from the rawacf file created.

Running the lag0 code on the files in the google drive returns the 'success' statement, but I can't comment further than that because I have no idea whats going on there.

**Comment by mts299** [comment]
[Help with the release of pyDARNio](https://trello.com/c/h6uAk3XS/28-help-with-the-release-of-pydarnio)

**Pull request merged**
